/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.twitch.twirp.example.Hat', null, global);
goog.exportSymbol('proto.twitch.twirp.example.Size', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.twitch.twirp.example.Hat = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.twitch.twirp.example.Hat, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.twitch.twirp.example.Hat.displayName = 'proto.twitch.twirp.example.Hat';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.twitch.twirp.example.Hat.prototype.toObject = function(opt_includeInstance) {
  return proto.twitch.twirp.example.Hat.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.twitch.twirp.example.Hat} msg The msg instance to transform.
 * @return {!Object}
 */
proto.twitch.twirp.example.Hat.toObject = function(includeInstance, msg) {
  var f, obj = {
    size: msg.getSize(),
    color: msg.getColor(),
    name: msg.getName()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.twitch.twirp.example.Hat}
 */
proto.twitch.twirp.example.Hat.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.twitch.twirp.example.Hat;
  return proto.twitch.twirp.example.Hat.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.twitch.twirp.example.Hat} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.twitch.twirp.example.Hat}
 */
proto.twitch.twirp.example.Hat.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSize(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setColor(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.twitch.twirp.example.Hat} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.twitch.twirp.example.Hat.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.twitch.twirp.example.Hat.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.twitch.twirp.example.Hat.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getSize();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = this.getColor();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.twitch.twirp.example.Hat} The clone.
 */
proto.twitch.twirp.example.Hat.prototype.cloneMessage = function() {
  return /** @type {!proto.twitch.twirp.example.Hat} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 size = 1;
 * @return {number}
 */
proto.twitch.twirp.example.Hat.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.twitch.twirp.example.Hat.prototype.setSize = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string color = 2;
 * @return {string}
 */
proto.twitch.twirp.example.Hat.prototype.getColor = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.twitch.twirp.example.Hat.prototype.setColor = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.twitch.twirp.example.Hat.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.twitch.twirp.example.Hat.prototype.setName = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.twitch.twirp.example.Size = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.twitch.twirp.example.Size, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.twitch.twirp.example.Size.displayName = 'proto.twitch.twirp.example.Size';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.twitch.twirp.example.Size.prototype.toObject = function(opt_includeInstance) {
  return proto.twitch.twirp.example.Size.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.twitch.twirp.example.Size} msg The msg instance to transform.
 * @return {!Object}
 */
proto.twitch.twirp.example.Size.toObject = function(includeInstance, msg) {
  var f, obj = {
    inches: msg.getInches()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.twitch.twirp.example.Size}
 */
proto.twitch.twirp.example.Size.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.twitch.twirp.example.Size;
  return proto.twitch.twirp.example.Size.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.twitch.twirp.example.Size} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.twitch.twirp.example.Size}
 */
proto.twitch.twirp.example.Size.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInches(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.twitch.twirp.example.Size} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.twitch.twirp.example.Size.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.twitch.twirp.example.Size.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.twitch.twirp.example.Size.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getInches();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.twitch.twirp.example.Size} The clone.
 */
proto.twitch.twirp.example.Size.prototype.cloneMessage = function() {
  return /** @type {!proto.twitch.twirp.example.Size} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 inches = 1;
 * @return {number}
 */
proto.twitch.twirp.example.Size.prototype.getInches = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.twitch.twirp.example.Size.prototype.setInches = function(value) {
  jspb.Message.setField(this, 1, value);
};


goog.object.extend(exports, proto.twitch.twirp.example);
